# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-04 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsandattributes', '0001_initial'),
        ('lifestyleuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settingsandattributes.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settingsandattributes.Country')),
                ('hosttype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settingsandattributes.HostTypes')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settingsandattributes.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifestyleuser.LifestyleUser')),
            ],
        ),
    ]
