# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsandattributes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingerSignupDeclineReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
