# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingsandattributes', '0004_swingerbodytypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwingerBodyTypes',
        ),
    ]
