# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-06 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsandattributes', '0001_initial'),
        ('swingers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='birthday1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='birthday2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='ethnicity1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ethnicity1', to='settingsandattributes.SwingerEthnicgroups'),
        ),
        migrations.AddField(
            model_name='swinger',
            name='ethnicity2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ethnicity2', to='settingsandattributes.SwingerEthnicgroups'),
        ),
        migrations.AddField(
            model_name='swinger',
            name='sex1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='swingersex1', to='settingsandattributes.SexType'),
        ),
        migrations.AddField(
            model_name='swinger',
            name='sex2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='swingersex2', to='settingsandattributes.SexType'),
        ),
        migrations.AddField(
            model_name='swinger',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='verificationphoto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
