# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0002_auto_20190106_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='verificationphotocode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='verificationphotokey',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
