# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0003_auto_20190114_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='wantcouplemanman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantcouplemants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantcouplemanwoman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantcoupletsts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantcouplewomants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantcouplewomanwoman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantsingleman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantsinglets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantsinglewoman',
            field=models.BooleanField(default=False),
        ),
    ]
