# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-27 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsandattributes', '0003_sexualorientation'),
        ('swingers', '0004_auto_20190212_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='orientation1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orientation1', to='settingsandattributes.SexualOrientation'),
        ),
        migrations.AddField(
            model_name='swinger',
            name='orientation2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orientation2', to='settingsandattributes.SexualOrientation'),
        ),
    ]
