# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0005_auto_20190227_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='wantasian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantblack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wanthispanic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantlatino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantnativeamerican',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantpacificislander',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantwhite',
            field=models.BooleanField(default=False),
        ),
    ]
