# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-02 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0006_auto_20190301_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='maxpreferedage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='minpreferedage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
