# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0007_auto_20190302_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='allownonoptinbodytypeusers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='bodytypesubmissiondate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='bodytypeverificationphoto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='bodytypeverificationphotocode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='bodytypeverificationphotokey',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='optinbodytypefiltering',
            field=models.BooleanField(default=False),
        ),
    ]
