# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0008_auto_20190303_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='isafewextrapoundsbodytype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isathleticbodytype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isaveragebodytype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isbodybuilderbodytype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isheavysetbodytype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantsafewextrapoundsbodytype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantsathleticbodytype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantsbodybuilderbodytype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantsheavysetbodytype',
            field=models.BooleanField(default=False),
        ),
    ]
