# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0009_auto_20190303_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='wantsaveragebodytype',
            field=models.BooleanField(default=False),
        ),
    ]
