# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0010_swinger_wantsaveragebodytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='bodytypeawaitingdecision',
            field=models.BooleanField(default=False),
        ),
    ]
