# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0012_swinger_bodytypefilteractive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swinger',
            old_name='isafewextrapoundsbodytype',
            new_name='isafewextrapoundsbodytype1',
        ),
        migrations.RenameField(
            model_name='swinger',
            old_name='isathleticbodytype',
            new_name='isafewextrapoundsbodytype2',
        ),
        migrations.RenameField(
            model_name='swinger',
            old_name='isaveragebodytype',
            new_name='isathleticbodytype1',
        ),
        migrations.RenameField(
            model_name='swinger',
            old_name='isbodybuilderbodytype',
            new_name='isathleticbodytype2',
        ),
        migrations.RenameField(
            model_name='swinger',
            old_name='isheavysetbodytype',
            new_name='isaveragebodytype1',
        ),
        migrations.AddField(
            model_name='swinger',
            name='isaveragebodytype2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isbodybuilderbodytype1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isbodybuilderbodytype2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isheavysetbodytype1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isheavysetbodytype2',
            field=models.BooleanField(default=False),
        ),
    ]
