# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0013_auto_20190304_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='iscurvybodytype1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='iscurvybodytype2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isthinbodytype1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='isthinbodytype2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantscurvybodytype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantsthinbodytype',
            field=models.BooleanField(default=False),
        ),
    ]
