# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-07 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0015_auto_20190306_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='istranny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swinger',
            name='wantstranny',
            field=models.BooleanField(default=False),
        ),
    ]
