# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0017_auto_20190422_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
