# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0018_swinger_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swinger',
            name='headline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
