# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingers', '0019_auto_20190423_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='swinger',
            name='coverphoto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='coverphotokey',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='profilephoto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='swinger',
            name='profilephotokey',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
