# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-05 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyleuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyleuser',
            name='prelaunchsignup',
            field=models.BooleanField(default=False),
        ),
    ]
